services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: claim_process_app
    ports:
      - "8000:8000"
    command: >
      bash -c "/app/wait-for-it.sh db:5432 -- echo 'db is up' &&
               /app/wait-for-it.sh redis:6379 -- echo 'redis is up' &&
               python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://claim_user:claim_password@db/claims_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: claim_process_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: claim_user
      POSTGRES_PASSWORD: claim_password
      POSTGRES_DB: claims_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d/

  redis:
    image: redis:latest
    container_name: claim_process_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: