
# This is the test specific docker-compose file used by the test suite.
services:
  app_test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: test_claim_process_app
    ports:
      - "8001:8000"
    command: >
      bash -c "/app/wait-for-it.sh db_test:5432 -- echo 'db_test is up' &&
               /app/wait-for-it.sh redis_test:6379 -- echo 'redis_test is up' &&
               python -m db.init_db && uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://test_user:test_password@db_test/test_claims_db
      - REDIS_URL=redis://redis_test:6379
    depends_on:
      - db_test
      - redis_test
    volumes:
      - .:/app

  db_test:
    image: postgres:15
    container_name: claim_process_db_test
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_claims_db
    volumes:
      - ./data/test_db:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d/

  redis_test:
    image: redis:latest
    container_name: claim_process_redis_test
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data

volumes:
  postgres_data:
  redis_test_data: