services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile  # Path to Dockerfile
    container_name: claim_process_app
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    command: >
      bash -c "/app/wait-for-it.sh db:5432 -- python init_db.py && 
      uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://claim_user:claim_password@db/claims_db
    depends_on:
      - db  # Ensures database starts before the app
    volumes:
      - .:/app  # Mount the local project directory (optional for development)

  db:
    image: postgres:15
    container_name: claim_process_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: claim_user
      POSTGRES_PASSWORD: claim_password
      POSTGRES_DB: claims_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d/

volumes:
  postgres_data: